### ISSUE TITLE
Can't load out of timerun with other save slots

### ISSUE THREAD

**Issue by ovska** [etjump/etjump#1276]
If your `save 2` or a previous save (`backup`) is _not_ in a timerun, you cannot load to it ("Save slots/backup is not enabled for this timerun"), despite the fact that loading them would pull you out of the run. Currently you can only load out of such timeruns with normal `load`

**Comment by Aciz** [comment]
This is partially addressed in #1289 

It's now possible to load out of no backup/save slots runs if an alternate save slot (slots 1-3) was saved into outside of the timerun as you'd expect. However backups are still restricted. This is because the backup queue is shared between all save slots (there's no separate backup queue for slot 0, slot 1, slot 2 etc) and when you start a timerun, the backup queue is cleared of any slots that are made during a timerun. This means that backup would always pull you out of a timerun, provided you have not overwritten all backup slots during the timerun already, which does not seem like a good idea and probably just causes confusion. The main issue here as I see it anyway was that you couldn't do a "timerun start save" with additional save slots when backups/saveslots were disabled in order to reset a run, but this is now addressed. Imo this is a good enough solution, feel free to close this if you agree.

**Comment by Aciz** [comment]
Solved sufficiently.
