### ISSUE TITLE
Worldspawn key to gib players stuck inside walls

### ISSUE THREAD

**Issue by ovska** [etjump/etjump#574]
Worldspawn setting such as `"nowallstuck" "1"` that would gib players if they are continuously inside a solid for over a certain amount of time (250-300ms?).

**Implementation:** In `PM_CorrectAllSolid` save `stuckTime` to pmext and send GIB event if stuck for too long. Reset `stuckTime` in `PM_GroundTrace` when `PM_CorrectAllSolid` is not called (or manages to fix the stuck).

**Comment by Aciz** [comment]
Curious as to why this is needed though, seeing ETJump already prevents head stucking with stance loading, and implementing something like this for any new feature that might need it is pretty trivial since such feature already exists for stuff such as constructibles. Only use case I can think of is to prevent prone bugging in walls, which can already be prevented with noprone.

**Comment by Aciz** [comment]
Side note: DeFRaG implements this feature with a server cvar `g_killWallBug` but might be problematic in ETJump if it's triggered from prone bugging due to some maps requiring it (distillery, sunrise, tjumps2 for example)

**Comment by ovska** [comment]
To prevent pmove 0 and/or low fps prone bugging. Something like this has to be implemented with #573 anyways so I thought it could also affect brushes in general, not just phasers.


> might be problematic in ETJump if it's triggered from prone bugging due to some maps requiring it

Set with worldspawn key with default being off, it shouldn't affect existing maps in any way.
