### ISSUE TITLE
Game restart crashes local etjump server

### ISSUE THREAD

**Issue by suburbski** [etjump/etjump#784]
```
game_restart etmain
----- Server Shutdown (Game directory changed) -----
********************
ERROR: MapStatistics::saveChanges: Error: Failed to update map. (1) no such table: map_statistics.

********************
----- Server Shutdown (Server crashed: MapStatistics::saveChanges: Error: Failed to update map. (1) no such table: map_statistics.
) -----
Sys_Error: recursive error after: MapStatistics::saveChanges: Error: Failed to update map. (1) no such table: map_statistics.
```

**Comment by Aciz** [comment]
This is likely fixed in next ET: Legacy release https://github.com/etlegacy/etlegacy/commit/8046c9544f0cbbcf8a2f12d6709ebf8babf29eb9

I've only ever encountered the path corruption while using ET: Legacy, and `game_restart` breaking shit is just likely same core issue as in #780 

Re-opening this if the error still pops up after ET: Legacy does a new release.
