### ISSUE TITLE
Event EV_LOAD_TELEPORT is dropped upon team change with autoload

### ISSUE THREAD

**Issue by suburbski** [etjump/etjump#838]
Joining a team from spectator works fine, but switching between Axis/Allies drops the event

**Comment by Aciz** [comment]
The issue happens somewhere in the team transition, likely because swapping between axis <-> allies calls `player_die` unlike spec -> axis/allies, suspecting there's some place where the events are cleared and dropped before client has a chance to receive the event. On server side and inside save system everything seems fine, the event does get added correctly, and to correct client, but the client simply never receives it. It's not dropping due to `MAX_EVENTS` either, there are only 2 events happening (max is 4 per frame).

**Comment by Aciz** [comment]
Actually this is simply caused by the fact that autoload is only processed in `SpectatorClientEndFrame` so autoload never gets triggered when switching between teams.

https://github.com/etjump/etjump/blob/012edfae16f9556e738031cc98f2978aaab1cd79/src/game/g_active.cpp#L1549-L1576
